#!/bin/sh
if ! command -v git-lfs >/dev/null 2>&1; then
  printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the '.husky/pre-push' file."
  exit 2
fi
git lfs pre-push "$@"